# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-01 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024, verbose_name='Name')),
                ('name_ru', models.CharField(max_length=1024, null=True, verbose_name='Name')),
                ('name_en', models.CharField(max_length=1024, null=True, verbose_name='Name')),
                ('code', models.CharField(db_index=True, max_length=2, verbose_name='IATA 2 chars code')),
                ('description', models.TextField(verbose_name='Decription')),
                ('description_ru', models.TextField(null=True, verbose_name='Decription')),
                ('description_en', models.TextField(null=True, verbose_name='Decription')),
                ('baggage_allowance_link', models.URLField(verbose_name='Baggage allowance link')),
                ('baggage_allowance_link_ru', models.URLField(null=True, verbose_name='Baggage allowance link')),
                ('baggage_allowance_link_en', models.URLField(null=True, verbose_name='Baggage allowance link')),
                ('carryon_max_x', models.FloatField(verbose_name='Carryon max length')),
                ('carryon_max_y', models.FloatField(verbose_name='Carryon max width')),
                ('carryon_max_z', models.FloatField(verbose_name='Carryon max height')),
                ('baggage_3dimensions', models.FloatField(verbose_name='Max value for the sum of 3 dimensions')),
                ('icon', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icon', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo icon 50x50')),
                ('logo', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo', to=settings.FILER_IMAGE_MODEL, verbose_name='Logo image [large]')),
            ],
            options={
                'verbose_name': 'Airline company',
                'verbose_name_plural': 'Airline companies',
                'ordering': ('name', 'code'),
            },
        ),
    ]
