# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-02 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_my_baggage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airlinecompany',
            name='baggage_3dimensions',
            field=models.FloatField(default=203.0, verbose_name='Max value for the sum of 3 dimensions'),
        ),
        migrations.AlterField(
            model_name='airlinecompany',
            name='carryon_max_x',
            field=models.FloatField(default=55.0, verbose_name='Carryon max length'),
        ),
        migrations.AlterField(
            model_name='airlinecompany',
            name='carryon_max_y',
            field=models.FloatField(default=40.0, verbose_name='Carryon max width'),
        ),
        migrations.AlterField(
            model_name='airlinecompany',
            name='carryon_max_z',
            field=models.FloatField(default=20.0, verbose_name='Carryon max height'),
        ),
        migrations.AlterField(
            model_name='airlinecompany',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Decription'),
        ),
        migrations.AlterField(
            model_name='airlinecompany',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Decription'),
        ),
        migrations.AlterField(
            model_name='airlinecompany',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Decription'),
        ),
    ]
